# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(choices=[('Band', 'Band'), ('Solo', 'Solo')], default='Band', max_length=14)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Dance', 'Dance'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Funk', 'Funk'), ('Trad', 'Trad'), ('Country', 'Country'), ('Soul', 'Soul'), ('RnB', 'RnB'), ('Other', 'Other')], default='Rock', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
