# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='profileImage',
            field=models.ImageField(default='media/no_image.png', upload_to='media/profile/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='profileImage2',
            field=models.ImageField(default='media/no_image.png', upload_to='media/profile/%Y/%m/%d'),
        ),
    ]
