# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainer', '0003_remove_entertainer_profileimage2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='profileImage',
            field=models.ImageField(default='media/no_image.png', upload_to='entertainers/static/entertainers/media/images/profile/'),
        ),
    ]
