# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Donabate', max_length=40),
        ),
    ]
