# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171204_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_entertainer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
